//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazek.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bets
    {
        public int id_bets { get; set; }
        public int id_session { get; set; }
        public int id_game { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Session Session { get; set; }
    }
}
