//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazek.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int id_transaction { get; set; }
        public int id_user { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string transaction_type { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
